name: build-nih-release
on:
  workflow_dispatch:
      inputs:
        tag:
          description: 'Tag to attach output to'
          required: true
jobs:
  build-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - run: mkdir -P output
      - name: build-main
        id: main
        run: ./build.sh main.tex
      - name: build-monsters
        id: monsters
        run: 
          ./build.sh monsters.tex
      - name: build-no-monsters
        id: no-monsters
        run: 
          ./build.sh no-monsters.tex
      - name: changelog
        id: changelog
        run: 
          ./build.sh changelog-only.tex
      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ github.event.inputs.tag }} output/*.pdf
        
        

